(use-modules (srfi srfi-1)
             (guix channels)
             (guix packages)
             (gnu home)
             (four-evy tooling)
             (four-evy system)
             (four-evy home)
             (four-evy channels))

(define (check condition message)
  (unless condition
    (error message)))

(check (pair? four-evy-tooling-packages) "Guix tooling package list is empty")
(define expected-package-names
  (sort (cons "brew-patches" four-evy-supported-tools) string<?))
(define tooling-package-names
  (sort (map package-name four-evy-tooling-packages) string<?))
(check (equal? expected-package-names tooling-package-names)
       "tooling package list does not match the support map")
(check (equal? (four-evy-system-packages) four-evy-tooling-packages)
       "system package composition is incomplete")
(check (equal? (home-environment-packages
                (four-evy-home-environment))
               four-evy-tooling-packages)
       "home package composition is incomplete")
(check (assoc-ref (package-inputs (car four-evy-tooling-packages))
                  "git-minimal")
       "brew-patches is missing its Git runtime input")
(check (assoc-ref (package-inputs (car four-evy-tooling-packages))
                  "bash-minimal")
       "brew-patches is missing its shell runtime input")
(check (equal? (map channel-name four-evy-channels) '(guix nonguix))
       "channel composition is incomplete")
(check (string=? (channel-url (car four-evy-channels))
                 "https://git.guix.gnu.org/guix.git")
       "Guix channel does not use its canonical project URL")
(check (string=? (channel-url (cadr four-evy-channels))
                 "https://gitlab.com/nonguix/nonguix")
       "Nonguix channel does not use its canonical upstream URL")
(display "Guix integration checks passed\n")
