# Generated by npins. Do not modify; it may be overwritten by npins.

let
  data = builtins.fromJSON (builtins.readFile ./sources.json);

  fetchSource =
    spec:
    builtins.fetchTarball {
      inherit (spec) url;
      sha256 = spec.hash;
    };
in
builtins.mapAttrs (_: fetchSource) data.pins
